from datetime import datetime
from html import escape

import pandas as pd
import streamlit as st

from ui import components
from ui.theme import inject_global_styles


def money(value) -> str:
    return f"Rs. {float(value):,.0f}"


def fmt_date(value) -> str:
    if not value:
        return "-"
    if isinstance(value, str):
        return value
    return value.strftime("%d %b %Y")


def status_badge(status: str) -> str:
    return components.status_badge(status)


def inject_css():
    inject_global_styles()


def metric_card(label: str, value: str):
    st.markdown(components.kpi_card(label, value), unsafe_allow_html=True)


def tour_card(tour, key_prefix: str, show_buttons=True):
    st.markdown(components.tour_card(tour), unsafe_allow_html=True)
    if show_buttons:
        cols = st.columns(2)
        if cols[0].button("View Details", key=f"{key_prefix}_details_{tour.id}", use_container_width=True):
            st.session_state.selected_tour_id = tour.id
            st.session_state.page = "Tour Details"
            st.rerun()
        if cols[1].button("Book Now", key=f"{key_prefix}_book_{tour.id}", type="primary", use_container_width=True):
            st.session_state.selected_tour_id = tour.id
            st.session_state.page = "Booking"
            st.rerun()


def dataframe_download(df: pd.DataFrame, label: str, filename: str):
    st.download_button(
        label,
        data=df.to_csv(index=False).encode("utf-8"),
        file_name=filename,
        mime="text/csv",
        use_container_width=True,
    )


def receipt_text(booking, payment=None) -> str:
    transaction_id = payment.transaction_id if payment else "-"
    paid_on = fmt_date(payment.payment_date) if payment else "-"
    return f"""TOUR MANAGEMENT SYSTEM - BOOKING RECEIPT
Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}

Booking ID: {booking.id}
Customer: {booking.user.name}
Tour: {booking.tour.title}
Destination: {booking.tour.destination}
Travel Date: {fmt_date(booking.travel_date)}
Travelers: {booking.travelers}
Total Amount: {money(booking.total_amount)}
Booking Status: {booking.status}
Payment Status: {booking.payment_status}
Transaction ID: {transaction_id}
Payment Date: {paid_on}

This receipt is generated by the offline simulated payment gateway for academic demonstration.
"""
